Execute script initializing WalletOwner after other scripts
keep-network/tbtc-v2 pull request #402
Opened 2022-08-12 14:19 UTC by michalinacienciala

The `initializeWalletOwner` function can be called only once per one
instance of `Bridge` contract. This means that once we run the deploy
script calling this function, we cannot successfully call it again using
same `ecdsa` package as a dependency. In our CI we run all the
deployment scripts from the `deploy` folder as a one step (they execute
in alphabetical order). If execution of some deployment script fails, we
re-run all the scripts again. If some script executed after `16_
initialize_wallet_owner.ts` would fail, we would not be able to simple
re-run the job deploying `tbtc-v2` contracts, but we would have to
publish a new `ecdsa` package to get fresh `Bridge` contract.
By renaming the `16_initialize_wallet_owner.ts` to
`90_initialize_wallet_owner.ts`, we move the execution of the script to
end, minimizing the risk of having to deploy a new `ecdsa` package.

2022-08-17 08:35 UTC, nkuba commented
I've just found out that I introduced similiar changes but forgot to create a PR (https://github.com/keep-network/tbtc-v2/commit/5cda93de4abf83ece835b49b708a688e0d70ff12) 🤦🏻 Could you also add `func.runAtTheEnd = true` in the script?

2022-08-17 08:36 UTC, nkuba requested changes
Please add `func.runAtTheEnd = true` in the `90_initialize_wallet_owner.ts` script.

2022-09-22 12:47 UTC, michalinacienciala commented
> Please add `func.runAtTheEnd = true` in the `90_initialize_wallet_owner.ts` script.

@nkuba, addressed, see [bf074d6](https://github.com/keep-network/tbtc-v2/pull/402/commits/bf074d6c38a9e7641ae1dba7e498fcdf3cb94745).

2022-09-23 06:41 UTC, nkuba approved these changes

2022-09-23 06:41 UTC, merged