TS: Support Blockstream's Esplora/Electrs servers for electrum protocol integration
keep-network/tbtc-v2 pull request #501
Opened 2023-01-25 22:47 UTC by nkuba

Closes: https://github.com/keep-network/tbtc-v2/issues/422

In this PR we update the implementation of TypeScript Electrum integration to support Esplora/Electrs servers.

As per https://github.com/Blockstream/electrs/pull/36 verbose transactions are not supported by Esplora/Electrs.
This affects our implementation of `getTransaction` and `getTransactionConfirmations` functions.

For a consistent code in the client without alternative paths for different Electrum servers implementations I decided to not use verbose transactions at all.

### [getTransactionConfirmations](https://github.com/keep-network/tbtc-v2/commit/26d4f0198fc964f49abbcf997777f89576d86b19)

1. Get the raw transaction
2. Deserialize the raw transaction
3. Find transaction block height by finding it in a history of
   transactions for the output script included in the transaction.
4. Get the latest block height
5. Calculate number of confirmations by subtracting the transaction
   block height from the latest block height and adding one.

### [getTransaction](https://github.com/keep-network/tbtc-v2/commit/a7aedd11fbfc7b26cbda5376a33207c7966f48bf)

We get a raw transaction and deserialize it with `bcoin`. This lets us define a consistent type for returned transactions (093d4ece7d2cd83d3d554a97d0985a67b7f4d154). Before these changes, I observed that Electrum server implementations are not consistent with data returned in verbose JSON.

### Electrum tests

We can test electrum integration against different kinds of servers.
The most popular implementations are:
- ElectrumX
- Fulcrum
- Electrs/Esplora

We can find a list of public servers here: https://1209k.com/bitcoin-eye/ele.php?chain=tbtc

The electrs-esplora server seems pretty unstable, so we don't want to enable it in tests until we add retries (https://github.com/keep-network/tbtc-v2/issues/485).

2023-01-26 08:21 UTC, nkuba commented
An alternative approach that I would also like to investigate would be to use verbose transactions as before and fallback to the logic proposed in this PR only in case verbose is not supported by the server.

2023-01-26 10:38 UTC, lukasz-zimnoch requested changes

2023-01-26 10:38 UTC, lukasz-zimnoch commented on typescript/src/electrum.ts
> +        const scriptHash: Buffer = output.script.sha256()
The `sha256` will not work in all cases. It produces a 32-byte script hash that is specific only to P2WSH. Other types P2SH, P2PKH, and P2WPKH use a 20-byte script computed using `hash160`.

2023-01-26 10:44 UTC, nkuba commented
> An alternative approach that I would also like to investigate would be to use verbose transactions as before and fallback to the logic proposed in this PR only in case verbose is not supported by the server.

I tested it and it did not result in any improvement in test execution time. This is probably as if we get verbose transactions the processing has to be done on the server side. Let's leave it as is and update it in the future if necessary.

2023-01-26 11:15 UTC, lukasz-zimnoch approved these changes

2023-01-26 11:16 UTC, merged

2023-01-27 18:32 UTC, shesek commented
> I tested it and it did not result in any improvement in test execution time

Interesting, I would've expected verbose transactions to perform better than fetching the entire address history and looking it up there.

Which electrum server implementation did you benchmark this against? Did you try with transactions that use reused addresses, such that looking up the address returns other historical transactions too?

(For example [`3ae54f00613ca0a39bbb202e49dc7f2abba9e5ed4c3fcdaed768c7effeeca403`](https://blockstream.info/tx/3ae54f00613ca0a39bbb202e49dc7f2abba9e5ed4c3fcdaed768c7effeeca403), which sends to an address with nearly 700k historical txs -- I guess it might not work at all if there are that many of them?)